version: "3.9"

services:
  backend:
    build: ./backend
    container_name: upostu_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/upostu

  postgres:
    image: postgres:16
    container_name: upostu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upostu
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

